[allowlist]
description = "Allowlist for non-sensitive caveat logs and chat history"
paths = [
  # Allow caveat message drops in repo root
  "^2025-.*-caveat-the-messages-.*\\.txt$",
  # Allow chat history files in docs directory
  "^docs/chat-history/.*\\.txt$"
]

