blank_issues_enabled: true
contact_links:
  - name: Security policy
    url: https://github.com/GiantCroissant-Lunar/breakout-coding-agent/security/policy
    about: Please read our security policy for reporting vulnerabilities.
