name: Assign Copilot to Game-RFC Issues

on:
  issues:
    types: [opened, reopened, labeled, edited]
  workflow_dispatch:
    inputs:
      issue:
        description: 'Specific issue number to (re)assign (optional)'
        required: false

permissions:
  issues: write

jobs:
  assign:
    # Run on:
    # - issues events where title/labels indicate a Game-RFC
    # - workflow_dispatch (manual backfill)
    if: |
      (github.event_name == 'issues' && (
        contains(github.event.issue.title, 'Game-RFC-') ||
        contains(join(github.event.issue.labels.*.name, ','), 'game-rfc')
      )) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - name: Get GitHub App token
      id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: Ensure Copilot is assigned (REST)
      run: |
        set -euo pipefail
        # Determine target issue(s)
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          if [ -n "${{ github.event.inputs.issue }}" ]; then
            ISSUE="${{ github.event.inputs.issue }}"
          else
            ISSUE=$(gh issue list --search "Game-RFC in:title" --label game-rfc --state open --limit 1 --sort created --json number --jq '.[0].number' || true)
          fi
        else
          ISSUE=${{ github.event.issue.number }}
        fi
        REPO=${{ github.repository }}
        echo "Checking assignment for issue #$ISSUE"
        ASSIGNEES=$(gh api repos/"$REPO"/issues/"$ISSUE" --jq '.assignees[].login' || true)
        if echo "$ASSIGNEES" | grep -Eq '^(copilot-swe-agent|Copilot)$'; then
          echo "Coding Agent already assigned"
          gh issue comment "$ISSUE" --repo "$REPO" --body "@copilot please start implementation" || true
          exit 0
        fi
        echo "Assigning Coding Agent via REST"
        gh api repos/"$REPO"/issues/"$ISSUE"/assignees -X POST -f assignees[]=copilot-swe-agent \
          || gh api repos/"$REPO"/issues/"$ISSUE"/assignees -X POST -f assignees[]=Copilot \
          || echo "Warning: could not assign Coding Agent (copilot-swe-agent/Copilot)"
        gh issue comment "$ISSUE" --repo "$REPO" --body "@copilot please start implementation" || true
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
