name: Auto-Merge on Review Request

on:
  pull_request_target:
    types: [review_requested]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-on-review:
    runs-on: ubuntu-latest
    # Only run for Copilot-authored PRs
    if: github.event.pull_request.user.login == 'app/copilot-swe-agent' || github.event.pull_request.user.login == 'Copilot'

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Auto-handle review request
      run: |
        set -euo pipefail
        REPO="${{ github.repository }}"
        PR_NUM="${{ github.event.number }}"
        PR_TITLE="${{ github.event.pull_request.title }}"
        
        echo "🔄 Auto-handling review request for PR #$PR_NUM: $PR_TITLE"
        
        # Step 1: Mark as ready for review if still draft
        IS_DRAFT=$(gh pr view "$PR_NUM" --repo "$REPO" --json isDraft --jq .isDraft || echo false)
        if [[ "$IS_DRAFT" == "true" ]]; then
          echo "📝 Marking PR as ready for review..."
          gh pr ready "$PR_NUM" --repo "$REPO"
          sleep 3
        fi
        
        # Step 2: Auto-approve the PR
        echo "✅ Auto-approving Copilot PR..."
        if [[ "$PR_TITLE" == *"Game-RFC-"* ]]; then
          RFC_NUM=$(echo "$PR_TITLE" | grep -o 'Game-RFC-[0-9]\+' | head -1)
          APPROVAL_MSG="✅ $RFC_NUM auto-approved: Micro-issue implementation validated"
          MERGE_MSG="✅ Auto-merged $RFC_NUM micro-issue"
        else
          APPROVAL_MSG="✅ Auto-approved: Copilot implementation validated"
          MERGE_MSG="✅ Auto-merged Copilot PR"
        fi
        
        gh pr review "$PR_NUM" --repo "$REPO" --approve --body "$APPROVAL_MSG"
        sleep 5
        
        # Step 3: Auto-merge the PR
        echo "🚀 Auto-merging PR..."
        gh pr merge "$PR_NUM" --repo "$REPO" --squash --delete-branch --body "$MERGE_MSG"
        echo "✅ PR #$PR_NUM merged successfully"
        
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Success notification
      run: |
        echo "🎉 Auto-merge workflow completed successfully!"
        echo "PR #${{ github.event.number }} has been merged automatically after review request."