name: Auto-Assign Next Micro-Issue

on:
  pull_request_target:
    types: [closed]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  assign-next-micro-issue:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Assign next micro-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number || '' }}
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "🔄 Manual trigger: Looking for recently merged PRs to process"
            # For manual trigger, find the most recent merged PR
            RECENT_PR=$(gh pr list --state merged --limit 1 --json number --jq '.[0].number // ""')
            if [[ -n "$RECENT_PR" ]]; then
              export PR_NUMBER="$RECENT_PR"
              echo "Found recent merged PR: #$RECENT_PR"
            else
              echo "❌ No recent merged PRs found"
              exit 0
            fi
          fi
          python .github/scripts/assign_next_micro_issue.py