name: Copilot Setup Steps

on:
  workflow_call:

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
          
      - name: Restore dependencies
        run: |
          cd dotnet/game
          dotnet restore
          
      - name: Setup development environment
        run: |
          echo "Development environment ready for GitHub Copilot"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          
      - name: Verify project structure
        run: |
          echo "Checking project structure..."
          ls -la dotnet/game/
          if [ -f "dotnet/game/Breakout.Game/Program.cs" ]; then
            echo "✅ Main project found"
          else
            echo "❌ Main project not found"
            exit 1
          fi