name: Gitleaks

on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          # Required for organization-owned repos. Set in repo/org secrets.
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        with:
          args: >
            detect
            --redact
            --verbose
            --report-format sarif
            --report-path gitleaks.sarif
            --config .github/gitleaks.toml

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always() && hashFiles('gitleaks.sarif') != ''
        with:
          sarif_file: gitleaks.sarif

      - name: Keep artifact (redacted)
        uses: actions/upload-artifact@v4
        if: always() && hashFiles('gitleaks.sarif') != ''
        with:
          name: gitleaks-sarif
          path: gitleaks.sarif
          retention-days: 7

