name: RFC Progression - Auto Create Next Game-RFC Issue

on:
  pull_request:
    types: [closed]
    branches: [main]
  
  # Allow manual trigger for testing
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force create next RFC issue'
        required: false
        default: 'false'

permissions:
  contents: write
  issues: write
  pull-requests: read

jobs:
  create-next-rfc:
    runs-on: ubuntu-latest
    if: |
      (github.event.pull_request.merged == true && 
       startsWith(github.head_ref, 'copilot/') && 
       contains(github.event.pull_request.title, 'Game-RFC-')) ||
      github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # No additional dependencies needed - using only stdlib and gh CLI
        
    - name: Analyze merged PR
      if: github.event_name == 'pull_request'
      run: |
        echo "📋 Analyzing merged Game-RFC PR..."
        echo "PR Title: ${{ github.event.pull_request.title }}"
        echo "PR Number: ${{ github.event.number }}"
        echo "Head Branch: ${{ github.head_ref }}"
        echo "Merged: ${{ github.event.pull_request.merged }}"
        
        # Extract RFC number from PR title
        RFC_NUM=$(echo "${{ github.event.pull_request.title }}" | grep -o 'Game-RFC-[0-9]\+' | grep -o '[0-9]\+' || echo "unknown")
        echo "Completed RFC Number: $RFC_NUM"
        echo "RFC_COMPLETED=$RFC_NUM" >> $GITHUB_ENV
        
    - name: Run RFC progression analysis
      run: |
        echo "🔍 Running intelligent RFC progression analysis..."
        
        # Make script executable
        chmod +x .github/scripts/create_next_rfc_issue.py
        
        # Run the Python script
        python .github/scripts/create_next_rfc_issue.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update RFC status documentation
      if: success()
      run: |
        echo "📚 Updating RFC documentation status..."
        
        # Check if there are any changes to commit
        if git diff --quiet; then
          echo "No documentation updates needed"
        else
          # Configure git for automated commits
          git config user.name "RFC Progression Bot"
          git config user.email "noreply@github.com"
          
          # Commit any documentation updates
          git add docs/
          git commit -m "docs: auto-update RFC status after progression
          
          Updated by RFC Progression workflow after Game-RFC completion.
          
          🤖 Generated by RFC Progression Workflow" || echo "No changes to commit"
          
          # Push changes
          git push || echo "No changes to push"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Comment on RFC Coordinator
      if: success()
      run: |
        echo "💬 Updating RFC Coordinator issue..."
        
        # Find RFC Coordinator issue (should be pinned)
        COORDINATOR_ISSUE=$(gh issue list --label coordinator --json number --jq '.[0].number' || echo "")
        
        if [ -n "$COORDINATOR_ISSUE" ]; then
          gh issue comment $COORDINATOR_ISSUE --body "## 🤖 RFC Progression Update
          
          **Trigger**: ${{ github.event_name }}
          **Workflow**: RFC Progression completed successfully
          **Time**: $(date -u +'%Y-%m-%d %H:%M:%S UTC')
          
          ### **Action Taken**
          ✅ Analyzed current Game-RFC state
          ✅ Identified next RFC ready for implementation  
          ✅ Created issue automatically if available
          ✅ Assigned to GitHub Coding Agent (@copilot)
          
          ### **Next Steps**
          The GitHub Coding Agent should automatically begin implementation of the newly created Game-RFC issue.
          
          ---
          
          **🔄 Automated by RFC Progression Workflow**"
        else
          echo "RFC Coordinator issue not found"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Summary
      if: always()
      run: |
        echo "📊 RFC Progression Workflow Summary"
        echo "================================="
        echo "Trigger: ${{ github.event_name }}"
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "Merged PR: ${{ github.event.pull_request.title }}"
          echo "Completed RFC: ${RFC_COMPLETED:-unknown}"
        fi
        echo "Status: ${{ job.status }}"
        echo ""
        echo "🎯 This workflow enables true end-to-end automation:"
        echo "   Game-RFC-001 → Game-RFC-002 → Game-RFC-003 → Game-RFC-004 → Game-RFC-005"
        echo "   All without manual intervention after the initial RFC-001 issue creation."
